### ISSUE TITLE
Construct "pipelines" corresponding to table of numerical experiments

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CL-SBI#6]
- [x] Create table of parameter variations (e.g. priors, m-c relations, richness-mass, etc.) to iterate on
- [x] Have an example json file for the first or first two rows of "experiments"

**Comment by akumgill** [comment]
Table of param variations: https://docs.google.com/spreadsheets/d/1mithxbcP7ovE7ph6_ZxtV8kVo5cFb4qdbi17IjJ8Giw/

Example json in the repo
